# /opt/newsletter/docker-compose.yml

version: '3.8'

services:
  # 1. Servizio API (Uvicorn)
  app:
    image: ghcr.io/wrprafra/newsletter-project:latest
    restart: always
    env_file:
      - .env
    # --- INIZIO MODIFICA ---
    environment:
      # Imposta il feature flag per disattivare la deduplicazione dei thread
      - THREAD_DEDUP_MODE=off
    # --- FINE MODIFICA ---
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /var/newsletter:/app/data
      - /opt/newsletter/secrets/credentials.json:/app/data/credentials.json:ro
    command:
      - uvicorn
      - backend.main:app
      - --host=0.0.0.0
      - --port=8000
      - --log-level=debug
      - --proxy-headers
      - --forwarded-allow-ips=*

  # 2. Servizio Worker (processa la coda)
  worker:
    image: ghcr.io/wrprafra/newsletter-project:latest
    restart: always
    depends_on:
      - redis
      - app
    env_file:
      - .env
    # --- INIZIO MODIFICA ---
    environment:
      # Il worker deve conoscere la stessa modalità per gestire correttamente i duplicati
      - THREAD_DEDUP_MODE=off
    # --- FINE MODIFICA ---
    volumes:
      - /var/newsletter:/app/data
      - /opt/newsletter/secrets/credentials.json:/app/data/credentials.json:ro
    command: python -m backend.worker

  # 3. Servizio Ingestor (popola la coda)
  ingestor:
    image: ghcr.io/wrprafra/newsletter-project:latest
    restart: always
    depends_on:
      - redis
      - app
    env_file:
      - .env
    # --- INIZIO MODIFICA ---
    environment:
      # L'ingestor deve sapere se saltare o meno i thread esistenti
      - THREAD_DEDUP_MODE=off
      # Aumentiamo i limiti per il backfill in produzione
      - INGESTOR_BACKFILL_PAGES=25
      - INGESTOR_BACKFILL_TARGET=1000
    # --- FINE MODIFICA ---
    volumes:
      - /var/newsletter:/app/data
      - /opt/newsletter/secrets/credentials.json:/app/data/credentials.json:ro
    command: python -m backend.ingestor

  # 4. Servizio Redis
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local