services:
  app:
    build: .
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env.dev
    ports: ["8000:8000"]
    depends_on: [redis]
    volumes:
      - ./:/app
      - ./data:/app/data

  worker:
    build: .
    command: python -m backend.worker
    env_file: .env.dev
    depends_on: [redis]
    volumes:
      - ./:/app
      - ./data:/app/data

  ingestor:
    build: .
    command: python -m backend.ingestor
    env_file: .env.dev
    depends_on: [redis]
    volumes:
      - ./:/app
      - ./data:/app/data

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]   # 6380 non serve in locale
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}
