services:
  app:
    image: ghcr.io/wrprafra/newsletter-project:latest
    env_file: /opt/newsletter/.env
    depends_on:
      - redis
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    
    volumes:
      # Monta la cartella dati. 'rw' è il default, quindi non serve specificarlo.
      - /var/newsletter:/app/data
      
      # Monta il file dei segreti in sola lettura.
      - /opt/newsletter/secrets/credentials.json:/app/data/credentials.json:ro

    command:
      - uvicorn
      - backend.main:app
      - --host=0.0.0.0
      - --port=8000
      - --log-level=debug
      - --proxy-headers
      - --forwarded-allow-ips=*

  redis:
    image: redis:7-alpine
    restart: always