services:
  app:
    image: ghcr.io/wrprafra/newsletter-project:latest
    env_file: /opt/newsletter/.env
    depends_on: [redis]
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      # QUESTA È LA RIGA DA AGGIUNGERE
      - ./backend/credentials.json:/app/backend/credentials.json:ro
      # QUESTA RIGA C'ERA GIÀ, LASCIALA
      - /var/newsletter/newsletter.db:/app/backend/newsletter.db
  redis:
    image: redis:7-alpine
    restart: always