name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Crea artefatto tar.gz
        run: |
          tar --exclude='.git' \
              --exclude='.github' \
              --exclude='.venv' \
              --exclude='.env' \
              --exclude='backend/newsletter.db' \
              -czf build.tar.gz .

      - name: Copia sul server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "build.tar.gz"
          target: "/opt/newsletter/upload/"

      - name: Deploy remoto
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -euo pipefail
            cd /opt/newsletter
            mkdir -p upload
            tar -xzf upload/build.tar.gz -C /opt/newsletter
            bash deploy.sh
