name: Deploy to Server

on:
  push:
    branches: [ "main" ] # Attivati solo sui push al branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to server with Rsync
        run: |
          rsync -az --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}/

      - name: Write version file
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "echo '${{ github.sha }} ' \$(date -u +'%Y-%m-%dT%H:%M:%SZ') > ${{ secrets.SERVER_PATH }}/frontend/version.txt"

      - name: Restart service on server
        run: ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "sudo systemctl restart ${{ secrets.SERVICE_NAME }}"