name: Deploy to Server
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show which workflow file is used
        run: |
          echo "Commit: $GITHUB_SHA"
          echo "::group::deploy.yml"
          sed -n '1,200p' .github/workflows/deploy.yml
          echo "::endgroup::"

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files to server (excluding local resources)
        run: |
          rsync -az --delete \
            --exclude '.git' \
            --exclude '.github' \
            --exclude 'node_modules' \
            --exclude '.venv/' \
            --exclude '.env' \
            --exclude 'backend/newsletter.db' \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}/

      - name: Install dependencies, restart, and verify service
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            set -euo pipefail
            set -x
            PROJECT_DIR="${{ secrets.SERVER_PATH }}"
            cd "$PROJECT_DIR"

            REQ_FILE="$PROJECT_DIR/requirements.txt"
            [ -f "$REQ_FILE" ] || { echo "requirements.txt in root mancante"; exit 1; }

            # venv pulita
            python3 -m venv "$PROJECT_DIR/.venv" || true
            . "$PROJECT_DIR/.venv/bin/activate"
            pip install -U pip

            # dipendenze progetto
            pip install -r "$REQ_FILE"

            # restart servizio
            sudo systemctl daemon-reload
            sudo systemctl restart ${{ secrets.SERVICE_NAME }} || \
              (sudo journalctl -xeu ${{ secrets.SERVICE_NAME }} --no-pager -n 200; exit 1)
            sleep 5
            systemctl --no-pager -l status ${{ secrets.SERVICE_NAME }}
          '